import Navbar from "@/components/Navbar";
import SidebarPage from "@/components/Sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body
					className={cn(
						inter.className,
						"select-none h-full w-full overflow-hidden bg-[#09090B]",
					)}>
					<ThemeProvider
						attribute='class'
						defaultTheme='dark'
						disableTransitionOnChange>
						<Navbar />
						{/* <Menubar /> */}
						<main className=' h-full mt-6 flex items-start justify-between gap-4 overflow-hidden'>
							<SidebarPage />
							{children}
							<Toaster />
						</main>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
